# Generated by Django 4.0.6 on 2022-08-04 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='addmovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('actor', models.CharField(max_length=100)),
                ('trailer', models.CharField(max_length=100)),
                ('poster', models.CharField(max_length=100)),
                ('user', models.CharField(max_length=100)),
                ('realeseddate', models.DateField()),
                ('description', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
    ]
