# Generated by Django 4.0.6 on 2022-08-04 18:26

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='addmovie',
            name='images',
            field=models.ImageField(default=builtins.print, upload_to='images'),
            preserve_default=False,
        ),
    ]
